services:
  app:
    build: .
    container_name: videoserver-app
    ports:
      - "${PORT:-3017}:3017"
    environment:
      - VIDEOS_PATH=${VIDEOS_PATH:-/data/videos}
    volumes:
      - E:/VideoServer/:/data/videos
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
